// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: ip_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IPServiceClient is the client API for IPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IPServiceClient interface {
	SendIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPResponse, error)
	GetIP(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IPResponse, error)
	SetIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	WatchIPUpdates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (IPService_WatchIPUpdatesClient, error)
}

type iPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIPServiceClient(cc grpc.ClientConnInterface) IPServiceClient {
	return &iPServiceClient{cc}
}

func (c *iPServiceClient) SendIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*IPResponse, error) {
	out := new(IPResponse)
	err := c.cc.Invoke(ctx, "/proto.IPService/SendIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) GetIP(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*IPResponse, error) {
	out := new(IPResponse)
	err := c.cc.Invoke(ctx, "/proto.IPService/GetIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) SetIP(ctx context.Context, in *IPRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.IPService/SetIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iPServiceClient) WatchIPUpdates(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (IPService_WatchIPUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &IPService_ServiceDesc.Streams[0], "/proto.IPService/WatchIPUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &iPServiceWatchIPUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IPService_WatchIPUpdatesClient interface {
	Recv() (*IPUpdate, error)
	grpc.ClientStream
}

type iPServiceWatchIPUpdatesClient struct {
	grpc.ClientStream
}

func (x *iPServiceWatchIPUpdatesClient) Recv() (*IPUpdate, error) {
	m := new(IPUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IPServiceServer is the server API for IPService service.
// All implementations must embed UnimplementedIPServiceServer
// for forward compatibility
type IPServiceServer interface {
	SendIP(context.Context, *IPRequest) (*IPResponse, error)
	GetIP(context.Context, *EmptyRequest) (*IPResponse, error)
	SetIP(context.Context, *IPRequest) (*EmptyResponse, error)
	WatchIPUpdates(*EmptyRequest, IPService_WatchIPUpdatesServer) error
	mustEmbedUnimplementedIPServiceServer()
}

// UnimplementedIPServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIPServiceServer struct {
}

func (UnimplementedIPServiceServer) SendIP(context.Context, *IPRequest) (*IPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIP not implemented")
}
func (UnimplementedIPServiceServer) GetIP(context.Context, *EmptyRequest) (*IPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIP not implemented")
}
func (UnimplementedIPServiceServer) SetIP(context.Context, *IPRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIP not implemented")
}
func (UnimplementedIPServiceServer) WatchIPUpdates(*EmptyRequest, IPService_WatchIPUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchIPUpdates not implemented")
}
func (UnimplementedIPServiceServer) mustEmbedUnimplementedIPServiceServer() {}

// UnsafeIPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IPServiceServer will
// result in compilation errors.
type UnsafeIPServiceServer interface {
	mustEmbedUnimplementedIPServiceServer()
}

func RegisterIPServiceServer(s grpc.ServiceRegistrar, srv IPServiceServer) {
	s.RegisterService(&IPService_ServiceDesc, srv)
}

func _IPService_SendIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).SendIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPService/SendIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).SendIP(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_GetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).GetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPService/GetIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).GetIP(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_SetIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IPServiceServer).SetIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IPService/SetIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IPServiceServer).SetIP(ctx, req.(*IPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IPService_WatchIPUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IPServiceServer).WatchIPUpdates(m, &iPServiceWatchIPUpdatesServer{stream})
}

type IPService_WatchIPUpdatesServer interface {
	Send(*IPUpdate) error
	grpc.ServerStream
}

type iPServiceWatchIPUpdatesServer struct {
	grpc.ServerStream
}

func (x *iPServiceWatchIPUpdatesServer) Send(m *IPUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// IPService_ServiceDesc is the grpc.ServiceDesc for IPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IPService",
	HandlerType: (*IPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendIP",
			Handler:    _IPService_SendIP_Handler,
		},
		{
			MethodName: "GetIP",
			Handler:    _IPService_GetIP_Handler,
		},
		{
			MethodName: "SetIP",
			Handler:    _IPService_SetIP_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchIPUpdates",
			Handler:       _IPService_WatchIPUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ip_service.proto",
}
